url: https://wer1.sg
baseurl: /

plugins:
- jekyll-seo-tag
- jekyll-sitemap

# Site settings
title: wer1
email: dana@wer1.sg
description: "Our one-stop services include accounting, tax, grant, payroll, workpass application, secretarial services and many more. Reach out to us to find out more!"

subtitle: Accounting • Tax • Grant
tagline: Leave The Mess to Expert

policy: https://ajar-cloudberry-4a0.notion.site/WER1-PTE-LTD-df01e886e2334270841a1c3473bd1c34

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100089296517849
  - title: whatsapp
    url: https://wa.me/6565144693?text=Hi%20Wer1,%20I%20would%20like%20to%20know%20more%20about%20the%20services.
  - title: linkedin
    url: https://www.linkedin.com/company/wer1sg/

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
